language: python

stages:
  - black
  - mypy
  - pylint
  - test
  - name: deploy
    if: tag IS present

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"
    - "$HOME/.cache/pre-commit"

install:
  - pip install pip -U
  - wget https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
  - python get-poetry.py -y
  - source $HOME/.poetry/env
  - poetry install -v

script: make test

python: "3.7"
dist: xenial

jobs:
  include:
    - python: "3.6"
      after_success: poetry run codecov
    - python: "3.7.0"
      dist: xenial
      after_success: poetry run codecov
    - python: "3.7.1"
      dist: xenial
      after_success: poetry run codecov

    - stage: Black
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files

    - stage: mypy
      script:
        - make mypy

    - stage: pylint
      script:
        - make lint

    - stage: deploy
      script:
        - poetry publish --username mholtzscher --password $PYPI_PASS --build
